# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='need',
            new_name='credit',
        ),
    ]
